### ISSUE TITLE
train_phocnet

### ISSUE THREAD

**Issue by gimsiang** [anuj-rai-23/PHOSC-Zero-Shot-Word-Recognition#1]
Hello!
I would like to ask if it is intended for -batch 10 -epoch 100 to cause the model to train less than 100 epochs. I have ran the following:
`python train_phocnet.py -id IAM_phoc -mp IAM_train.csv -vmap IAM_valid.csv -tr IAM_train -vi IAM_valid -batch 10 -epoch 100`
This causes the model to train over 4 epochs, as shown in the attached.
![phocnet](https://user-images.githubusercontent.com/123949113/215468364-008530e8-af75-4051-9428-bb3938106aa5.JPG)

I believe this is due to line 166, `EPOCHS=70000//STEPS+10000//STEPS+1`, as `STEPS` is dependent on the length of the data frame and batch size.

May I know if this is intended?

Thanks for the help.

**Comment by anuj-rai-23** [comment]
We reproduced the results produced by the original PhocNet paper, where they trained for a fixed no. of steps/iterations.
No of steps in an epoch = No. of samples/batch size
No. of Epochs needed can be computed with the help of this.
Hence, epochs will be the same for a given batch size and train set.

Line 166 can be omitted, and you can use epochs like other parameters.

**Comment by gimsiang** [comment]
Okay, thank you for the clarification.
