### ISSUE TITLE
Increasing the pyramid level

### ISSUE THREAD

**Issue by gimsiang** [anuj-rai-23/PHOSC-Zero-Shot-Word-Recognition#2]
Hello,

I understand that in this work, the pyramid has 5 levels.

Would it possible to increase the pyramid levels? How would I be able to do that?

Thank you for your help.

**Comment by anuj-rai-23** [comment]
Yes, it is possible to increase the levels of the pyramid. Or even use different levels, e.g., in the literature, some work has used [1,2,4,8] level. You will have to make a few adjustments to the following:
* Output layer size of the NN
* phos_label_generator.py/generate_label() function
